const questions = [
    {
        id: 1,
        domain: '1. Fisika',
        questionText: 'Apa yang dimaksud dengan induksi magnetik?',
        answerOptions: [
            { answerID: 'a', answerText: 'Pembangkitan arus listrik melalui medan magnet' },
            { answerID: 'b', answerText: 'Pengurangan medan magnet oleh konduktor' },
            { answerID: 'c', answerText: 'Pembentukan medan listrik oleh medan magnet' },
            { answerID: 'd', answerText: 'Penciptaan medan magnet oleh arus listrik' },
        ],
        correctResponse: 'a',
        questionRationale: 'Induksi magnetik adalah proses di mana arus listrik dihasilkan oleh perubahan medan magnet di sekitar konduktor.',
    },
    {
        id: 2,
        domain: '1. Fisika',
        questionText: 'Siapa yang menemukan hukum induksi elektromagnetik?',
        answerOptions: [
            { answerID: 'a', answerText: 'James Clerk Maxwell' },
            { answerID: 'b', answerText: 'Isaac Newton' },
            { answerID: 'c', answerText: 'Michael Faraday' },
            { answerID: 'd', answerText: 'Albert Einstein' },
        ],
        correctResponse: 'c',
        questionRationale: 'Michael Faraday menemukan hukum induksi elektromagnetik pada tahun 1831.',
    },
    {
        id: 3,
        domain: '1. Fisika',
        questionText: 'Apa yang terjadi ketika konduktor bergerak di dalam medan magnet?',
        answerOptions: [
            { answerID: 'a', answerText: 'Medan listrik konstan dihasilkan' },
            { answerID: 'b', answerText: 'Arus induksi dihasilkan' },
            { answerID: 'c', answerText: 'Medan magnet berhenti' },
            { answerID: 'd', answerText: 'Energi potensial meningkat' },
        ],
        correctResponse: 'b',
        questionRationale: 'Ketika konduktor bergerak di dalam medan magnet, arus induksi dihasilkan sesuai dengan hukum Faraday.',
    },
    {
        id: 4,
        domain: '1. Fisika',
        questionText: 'Apa satuan SI untuk fluks magnetik?',
        answerOptions: [
            { answerID: 'a', answerText: 'Tesla' },
            { answerID: 'b', answerText: 'Weber' },
            { answerID: 'c', answerText: 'Henry' },
            { answerID: 'd', answerText: 'Gauss' },
        ],
        correctResponse: 'b',
        questionRationale: 'Satuan SI untuk fluks magnetik adalah Weber (Wb).',
    },
    {
        id: 5,
        domain: '1. Fisika',
        questionText: 'Hukum Faraday menyatakan bahwa gaya gerak listrik (emf) yang diinduksi dalam suatu rangkaian sebanding dengan apa?',
        answerOptions: [
            { answerID: 'a', answerText: 'Luas penampang' },
            { answerID: 'b', answerText: 'Perubahan arus listrik' },
            { answerID: 'c', answerText: 'Perubahan medan magnet' },
            { answerID: 'd', answerText: 'Panjang konduktor' },
        ],
        correctResponse: 'c',
        questionRationale: 'Hukum Faraday menyatakan bahwa emf yang diinduksi dalam suatu rangkaian sebanding dengan laju perubahan medan magnet yang melingkupi rangkaian tersebut.',
    },
    {
        id: 6,
        domain: '2. Kimia',
        questionText: 'Apa yang dimaksud dengan diamagnetik?',
        answerOptions: [
            { answerID: 'a', answerText: 'Bahan yang tidak dapat dipengaruhi oleh medan magnet' },
            { answerID: 'b', answerText: 'Bahan yang ditarik kuat oleh medan magnet' },
            { answerID: 'c', answerText: 'Bahan yang menciptakan medan magnet sendiri' },
            { answerID: 'd', answerText: 'Bahan yang ditolak lemah oleh medan magnet' },
        ],
        correctResponse: 'd',
        questionRationale: 'Diamagnetik adalah bahan yang ditolak lemah oleh medan magnet karena tidak memiliki momen magnetik permanen.',
    },
    {
        id: 7,
        domain: '2. Kimia',
        questionText: 'Apa sifat magnetik dari bahan paramagnetik?',
        answerOptions: [
            { answerID: 'a', answerText: 'Ditolak kuat oleh medan magnet' },
            { answerID: 'b', answerText: 'Tidak dipengaruhi oleh medan magnet' },
            { answerID: 'c', answerText: 'Ditolak lemah oleh medan magnet' },
            { answerID: 'd', answerText: 'Ditarik lemah oleh medan magnet' },
        ],
        correctResponse: 'd',
        questionRationale: 'Bahan paramagnetik ditarik lemah oleh medan magnet karena memiliki momen magnetik yang tidak berpasangan.',
    },
    {
        id: 8,
        domain: '2. Kimia',
        questionText: 'Apa yang dimaksud dengan bahan feromagnetik?',
        answerOptions: [
            { answerID: 'a', answerText: 'Bahan yang hanya ditarik lemah oleh medan magnet' },
            { answerID: 'b', answerText: 'Bahan yang tidak dipengaruhi oleh medan magnet' },
            { answerID: 'c', answerText: 'Bahan yang menciptakan medan magnet sendiri tanpa pengaruh luar' },
            { answerID: 'd', answerText: 'Bahan yang ditarik kuat oleh medan magnet dan dapat menjadi magnet permanen' },
        ],
        correctResponse: 'd',
        questionRationale: 'Bahan feromagnetik ditarik kuat oleh medan magnet dan dapat menjadi magnet permanen, seperti besi, kobalt, dan nikel.',
    },
    {
        id: 9,
        domain: '2. Kimia',
        questionText: 'Apa yang terjadi pada domain magnetik dalam bahan feromagnetik ketika terkena medan magnet eksternal?',
        answerOptions: [
            { answerID: 'a', answerText: 'Domain magnetik menjadi acak' },
            { answerID: 'b', answerText: 'Domain magnetik sejajar dengan medan magnet eksternal' },
            { answerID: 'c', answerText: 'Domain magnetik mengecil' },
            { answerID: 'd', answerText: 'Domain magnetik hilang' },
        ],
        correctResponse: 'b',
        questionRationale: 'Dalam bahan feromagnetik, domain magnetik sejajar dengan medan magnet eksternal, menyebabkan bahan tersebut menjadi magnetik.',
    },
    {
        id: 10,
        domain: '2. Kimia',
        questionText: 'Siapa yang menemukan fenomena induksi magnetik?',
        answerOptions: [
            { answerID: 'a', answerText: 'James Clerk Maxwell' },
            { answerID: 'b', answerText: 'Isaac Newton' },
            { answerID: 'c', answerText: 'Michael Faraday' },
            { answerID: 'd', answerText: 'Albert Einstein' },
        ],
        correctResponse: 'c',
        questionRationale: 'Michael Faraday menemukan fenomena induksi magnetik pada tahun 1831.',
    }
];

export default questions;
